YAML update for dev deploy failed

diff --git a/.github/workflows/ci-cd-dev-prod.yml b/.github/workflows/ci-cd-dev-prod.yml
--- a/.github/workflows/ci-cd-dev-prod.yml
+++ b/.github/workflows/ci-cd-dev-prod.yml
@@ -17,7 +17,7 @@ jobs:
   runs-on: ubuntu-latest
 
   outputs:
-    image: ${{ steps.build.outputs.image }}
+    image: ${{ steps.export-image.outputs.image }}
 
   steps:
     - uses: actions/checkout@v4
@@ -30,20 +30,24 @@ jobs:
 
     - name: Configure Docker
       run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
-
+    
     - name: Normalize env vars
       run: |
         echo "PROJECT_ID=$(echo "$PROJECT_ID" | xargs)" >> $GITHUB_ENV
         echo "REGION=$(echo "$REGION" | xargs)" >> $GITHUB_ENV
-        
-    - name: Build & Push Image
-      id: build
+
+    - name: Build and Push
       run: |
         IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA"
-        echo "IMAGE=$IMAGE"
+        echo "Built image: $IMAGE"
         docker build -t "$IMAGE" .
         docker push "$IMAGE"
-        echo "image=$IMAGE" >> $GITHUB_OUTPUT
+
+    - name: Export image output
+      id: export-image
+      run: |
+        IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA"
+        echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
 
  deploy-dev:
     name: Deploy to DEV
@@ -58,14 +62,14 @@ jobs:
 
       - uses: google-github-actions/setup-gcloud@v2
 
-      - name: Validate env vars
+      - name: Validate image input
         run: |
-            echo "IMAGE=$(echo "$image" | xargs)"
-            echo "Checking image" 
-            echo "$GITHUB_OUTPUT"
-            echo "$image"
-            echo "$IMAGE"
-            echo "checked image"
+            echo "Image from build job: [${{ needs.build.outputs.image }}]"
+            if [ -z "${{ needs.build.outputs.image }}" ]; then
+            echo "❌ IMAGE IS EMPTY — failing fast"
+            exit 1
+            fi
+
 
       - name: Deploy DEV
         run: |
